-- 20260606000006_seed_agences.sql
-- Seed des 52 agences SALTI (nom, ville, code) extraites du document
-- "Les agences SALTI" via OCR (Gemini). À VÉRIFIER : l'OCR est fiable mais
-- quelques villes/codes peuvent nécessiter une correction manuelle dans
-- /admin/users (ex: Mulhouse était lue "Amiens" -> corrigée ici en Mulhouse).
-- À exécuter UNE SEULE FOIS (la table agences était vide).

insert into public.agences (nom, ville, code) values
('Amiens', 'Amiens', 'AM'),
('Arras', 'Arras', 'AR'),
('Avignon', 'Avignon', 'AV'),
('Bayonne', 'Bayonne', 'BY'),
('Beauvais', 'Beauvais', 'BV'),
('Béthune', 'Béthune', 'BE'),
('Bordeaux', 'Bordeaux', 'BX'),
('Boulogne', 'Boulogne', 'BL'),
('Bourges', 'Bourges', 'BO'),
('Caen', 'Caen', 'CN'),
('Calais', 'Calais', 'CA'),
('Cambrai', 'Cambrai', 'CR'),
('Clermont Ferrand', 'Clermont-Ferrand', 'CF'),
('Dijon', 'Dijon', 'DJ'),
('Douai', 'Douai', 'DO'),
('Dunkerque', 'Dunkerque', 'DK'),
('Grenoble', 'Grenoble', 'GB'),
('Lagny Le Sec', 'Lagny-le-Sec', 'LA'),
('Le Havre', 'Le Havre', 'HA'),
('Le Mans', 'Le Mans', 'MN'),
('Lens', 'Lens', 'LS'),
('Limoges', 'Limoges', 'LI'),
('Lomme Bases Vie', 'Lomme', 'OM'),
('Lomme', 'Lomme', 'LO'),
('Longjumeau', 'Longjumeau', 'LJ'),
('Lyon', 'Lyon', 'LY'),
('Marcq Agence', 'Marcq-en-Baroeul', 'MQ'),
('Marcq - Services Centraux', 'Marcq-en-Baroeul', 'SC'),
('Marseille', 'Marseille', 'MS'),
('Maubeuge', 'Maubeuge', 'MB'),
('Metz', 'Metz', 'MZ'),
('Mulhouse', 'Mulhouse', 'MU'),
('Mitry Mory', 'Mitry-Mory', 'LB'),
('Montpellier', 'Montpellier', 'MP'),
('Nancy', 'Nancy', 'NC'),
('Nantes', 'Nantes', 'NT'),
('Nice', 'Nice', 'NI'),
('Orléans', 'Orléans', 'OR'),
('Pau', 'Pau', 'PU'),
('Pontoise', 'Pontoise', 'PO'),
('Reims', 'Reims', 'RS'),
('Rennes', 'Rennes', 'RN'),
('Rouen', 'Rouen', 'RO'),
('Saint Etienne', 'Saint-Étienne', 'SA'),
('Saint Omer', 'Saint-Omer', 'SO'),
('Saint-Quentin', 'Saint-Quentin', 'SQ'),
('Strasbourg', 'Strasbourg', 'SG'),
('Toulon', 'Toulon', 'TN'),
('Toulouse', 'Toulouse', 'TO'),
('Tours', 'Tours', 'TR'),
('Valence', 'Valence', 'VL'),
('Valenciennes', 'Valenciennes', 'VA');
